version: "3"

services:
  postgres:
    image: postgres:9.5
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=allocation_matrix
    restart: always
  server:
    build: .
    volumes:
      - ./uploads:/usr/src/server/uploads
    ports:
      - 8040:8000
    links:
      - postgres:postgres
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_NAME=ekoskola_games
      - DB_PASS=postgres
      - DB_USE_SSL=false
      - DB_USER=postgres
      - DB_TIMEZONE=Europe/Berlin
      - DOCKER_ENABLE_CI=true
      - PORT=8080
      - SERVER_ENVIRONMENT=stagging
      - WEBSITES_ENABLE_APP_SERVICE_STORAGE=false
      - WEBSITES_PORT=8000
    depends_on:
      - postgres
    restart: on-failure
